-- Kör den här filen i Supabase SQL Editor innan appen används av flera personer.
-- Den samlar appens release-migrationer i rätt ordning.

alter table if exists public.kop
  add column if not exists source text not null default 'budget';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'kop_source_check'
  ) then
    alter table public.kop
      add constraint kop_source_check check (source in ('budget', 'free'));
  end if;
end $$;

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  title text not null,
  saved numeric not null default 0,
  target numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.savings_accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  amount numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.profile (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  full_name text,
  monthly_income numeric not null default 0,
  monthly_savings numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table if exists public.budgets
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.kop
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.categories
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.subscriptions
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.goals
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.savings_accounts
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.profile
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.profile
  add column if not exists full_name text;

alter table if exists public.profile
  add column if not exists monthly_income numeric not null default 0;

alter table if exists public.profile
  add column if not exists monthly_savings numeric not null default 0;

alter table if exists public.profile
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.savings_accounts
  drop constraint if exists savings_accounts_name_key;

create unique index if not exists savings_accounts_user_name_key
  on public.savings_accounts (user_id, lower(name));

create unique index if not exists profile_user_id_key
  on public.profile (user_id)
  where user_id is not null;

alter table if exists public.budgets enable row level security;
alter table if exists public.kop enable row level security;
alter table if exists public.categories enable row level security;
alter table if exists public.subscriptions enable row level security;
alter table if exists public.goals enable row level security;
alter table if exists public.savings_accounts enable row level security;
alter table if exists public.profile enable row level security;

drop policy if exists "Users can select their own budgets" on public.budgets;
drop policy if exists "Users can insert their own budgets" on public.budgets;
drop policy if exists "Users can update their own budgets" on public.budgets;
drop policy if exists "Users can delete their own budgets" on public.budgets;
create policy "Users can select their own budgets" on public.budgets for select using (auth.uid() = user_id);
create policy "Users can insert their own budgets" on public.budgets for insert with check (auth.uid() = user_id);
create policy "Users can update their own budgets" on public.budgets for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own budgets" on public.budgets for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own purchases" on public.kop;
drop policy if exists "Users can insert their own purchases" on public.kop;
drop policy if exists "Users can update their own purchases" on public.kop;
drop policy if exists "Users can delete their own purchases" on public.kop;
create policy "Users can select their own purchases" on public.kop for select using (auth.uid() = user_id);
create policy "Users can insert their own purchases" on public.kop for insert with check (auth.uid() = user_id);
create policy "Users can update their own purchases" on public.kop for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own purchases" on public.kop for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own categories" on public.categories;
drop policy if exists "Users can insert their own categories" on public.categories;
drop policy if exists "Users can update their own categories" on public.categories;
drop policy if exists "Users can delete their own categories" on public.categories;
create policy "Users can select their own categories" on public.categories for select using (auth.uid() = user_id);
create policy "Users can insert their own categories" on public.categories for insert with check (auth.uid() = user_id);
create policy "Users can update their own categories" on public.categories for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own categories" on public.categories for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own subscriptions" on public.subscriptions;
drop policy if exists "Users can insert their own subscriptions" on public.subscriptions;
drop policy if exists "Users can update their own subscriptions" on public.subscriptions;
drop policy if exists "Users can delete their own subscriptions" on public.subscriptions;
create policy "Users can select their own subscriptions" on public.subscriptions for select using (auth.uid() = user_id);
create policy "Users can insert their own subscriptions" on public.subscriptions for insert with check (auth.uid() = user_id);
create policy "Users can update their own subscriptions" on public.subscriptions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own subscriptions" on public.subscriptions for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own goals" on public.goals;
drop policy if exists "Users can insert their own goals" on public.goals;
drop policy if exists "Users can update their own goals" on public.goals;
drop policy if exists "Users can delete their own goals" on public.goals;
create policy "Users can select their own goals" on public.goals for select using (auth.uid() = user_id);
create policy "Users can insert their own goals" on public.goals for insert with check (auth.uid() = user_id);
create policy "Users can update their own goals" on public.goals for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own goals" on public.goals for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own savings accounts" on public.savings_accounts;
drop policy if exists "Users can insert their own savings accounts" on public.savings_accounts;
drop policy if exists "Users can update their own savings accounts" on public.savings_accounts;
drop policy if exists "Users can delete their own savings accounts" on public.savings_accounts;
create policy "Users can select their own savings accounts" on public.savings_accounts for select using (auth.uid() = user_id);
create policy "Users can insert their own savings accounts" on public.savings_accounts for insert with check (auth.uid() = user_id);
create policy "Users can update their own savings accounts" on public.savings_accounts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own savings accounts" on public.savings_accounts for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own profile" on public.profile;
drop policy if exists "Users can insert their own profile" on public.profile;
drop policy if exists "Users can update their own profile" on public.profile;
drop policy if exists "Users can delete their own profile" on public.profile;
create policy "Users can select their own profile" on public.profile for select using (auth.uid() = user_id);
create policy "Users can insert their own profile" on public.profile for insert with check (auth.uid() = user_id);
create policy "Users can update their own profile" on public.profile for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own profile" on public.profile for delete using (auth.uid() = user_id);

alter table if exists public.subscriptions
  add column if not exists frequency text not null default 'monthly';

alter table if exists public.subscriptions
  add column if not exists interval_months integer not null default 1;

alter table if exists public.subscriptions
  add column if not exists start_date date;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'subscriptions_frequency_check'
  ) then
    alter table public.subscriptions
      add constraint subscriptions_frequency_check
      check (frequency in ('monthly', 'quarterly', 'semiannual', 'yearly', 'custom'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'subscriptions_interval_months_check'
  ) then
    alter table public.subscriptions
      add constraint subscriptions_interval_months_check
      check (interval_months >= 1);
  end if;
end $$;

create table if not exists public.travel_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  budget numeric not null,
  start_date date not null,
  end_date date not null,
  separate_from_free_money boolean not null default true,
  created_at timestamptz not null default now(),
  constraint travel_budgets_budget_check check (budget > 0),
  constraint travel_budgets_date_check check (end_date >= start_date)
);

create table if not exists public.travel_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  travel_budget_id bigint not null references public.travel_budgets(id) on delete cascade,
  title text not null,
  amount numeric not null,
  category text not null default 'Övrigt',
  purchase_date date not null default current_date,
  created_at timestamptz not null default now(),
  constraint travel_purchases_amount_check check (amount > 0)
);

create index if not exists travel_budgets_user_start_date_idx
  on public.travel_budgets (user_id, start_date desc);

create index if not exists travel_purchases_budget_date_idx
  on public.travel_purchases (travel_budget_id, purchase_date desc);

alter table if exists public.travel_budgets enable row level security;
alter table if exists public.travel_purchases enable row level security;

drop policy if exists "Users can select their own travel budgets" on public.travel_budgets;
drop policy if exists "Users can insert their own travel budgets" on public.travel_budgets;
drop policy if exists "Users can update their own travel budgets" on public.travel_budgets;
drop policy if exists "Users can delete their own travel budgets" on public.travel_budgets;
create policy "Users can select their own travel budgets" on public.travel_budgets for select using (auth.uid() = user_id);
create policy "Users can insert their own travel budgets" on public.travel_budgets for insert with check (auth.uid() = user_id);
create policy "Users can update their own travel budgets" on public.travel_budgets for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own travel budgets" on public.travel_budgets for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own travel purchases" on public.travel_purchases;
drop policy if exists "Users can insert their own travel purchases" on public.travel_purchases;
drop policy if exists "Users can update their own travel purchases" on public.travel_purchases;
drop policy if exists "Users can delete their own travel purchases" on public.travel_purchases;
create policy "Users can select their own travel purchases" on public.travel_purchases for select using (auth.uid() = user_id);
create policy "Users can insert their own travel purchases" on public.travel_purchases for insert with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.travel_budgets
    where travel_budgets.id = travel_purchases.travel_budget_id
      and travel_budgets.user_id = auth.uid()
  )
);
create policy "Users can update their own travel purchases" on public.travel_purchases for update using (auth.uid() = user_id) with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.travel_budgets
    where travel_budgets.id = travel_purchases.travel_budget_id
      and travel_budgets.user_id = auth.uid()
  )
);
create policy "Users can delete their own travel purchases" on public.travel_purchases for delete using (auth.uid() = user_id);

alter table if exists public.kop
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.goals
  add column if not exists created_at timestamptz not null default now();

create index if not exists budgets_user_id_idx on public.budgets (user_id);
create index if not exists kop_user_created_idx on public.kop (user_id, created_at desc);
create index if not exists categories_user_name_idx on public.categories (user_id, lower(name));
create index if not exists subscriptions_user_day_idx on public.subscriptions (user_id, day_of_month);
create index if not exists goals_user_created_idx on public.goals (user_id, created_at);
create index if not exists savings_accounts_user_id_idx on public.savings_accounts (user_id);
create index if not exists profile_user_id_idx on public.profile (user_id);
create index if not exists travel_budgets_user_id_idx on public.travel_budgets (user_id);
create index if not exists travel_purchases_user_id_idx on public.travel_purchases (user_id);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  type text not null default 'bug',
  message text not null,
  page text,
  app_version text,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  constraint feedback_type_check check (type in ('bug', 'idea', 'question', 'other')),
  constraint feedback_status_check check (status in ('new', 'reviewed', 'planned', 'done', 'closed'))
);

create index if not exists feedback_user_created_idx
  on public.feedback (user_id, created_at desc);

create index if not exists feedback_status_created_idx
  on public.feedback (status, created_at desc);

alter table if exists public.feedback enable row level security;

drop policy if exists "Users can select their own feedback" on public.feedback;
drop policy if exists "Users can insert their own feedback" on public.feedback;
drop policy if exists "Users can update their own feedback" on public.feedback;
drop policy if exists "Users can delete their own feedback" on public.feedback;

create policy "Users can select their own feedback" on public.feedback for select using (auth.uid() = user_id);
create policy "Users can insert their own feedback" on public.feedback for insert with check (auth.uid() = user_id);
create policy "Users can update their own feedback" on public.feedback for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own feedback" on public.feedback for delete using (auth.uid() = user_id);

alter table if exists public.feedback
  drop constraint if exists feedback_type_check;

alter table if exists public.feedback
  add constraint feedback_type_check check (type in ('bug', 'idea', 'question', 'other'));

drop policy if exists "Admins can select all feedback" on public.feedback;
drop policy if exists "Admins can update all feedback" on public.feedback;

create policy "Admins can select all feedback" on public.feedback for select using (
  lower(auth.jwt() ->> 'email') in ('oskarek575@gmail.com', 'oskarcool1337@gmail.com')
);

create policy "Admins can update all feedback" on public.feedback for update using (
  lower(auth.jwt() ->> 'email') in ('oskarek575@gmail.com', 'oskarcool1337@gmail.com')
) with check (
  lower(auth.jwt() ->> 'email') in ('oskarek575@gmail.com', 'oskarcool1337@gmail.com')
);
