alter table if exists public.subscriptions
  add column if not exists frequency text not null default 'monthly';

alter table if exists public.subscriptions
  add column if not exists interval_months integer not null default 1;

alter table if exists public.subscriptions
  add column if not exists start_date date;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'subscriptions_frequency_check'
  ) then
    alter table public.subscriptions
      add constraint subscriptions_frequency_check
      check (frequency in ('monthly', 'quarterly', 'semiannual', 'yearly', 'custom'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'subscriptions_interval_months_check'
  ) then
    alter table public.subscriptions
      add constraint subscriptions_interval_months_check
      check (interval_months >= 1);
  end if;
end $$;

create table if not exists public.travel_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  budget numeric not null,
  start_date date not null,
  end_date date not null,
  separate_from_free_money boolean not null default true,
  created_at timestamptz not null default now(),
  constraint travel_budgets_budget_check check (budget > 0),
  constraint travel_budgets_date_check check (end_date >= start_date)
);

create table if not exists public.travel_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  travel_budget_id bigint not null references public.travel_budgets(id) on delete cascade,
  title text not null,
  amount numeric not null,
  category text not null default 'Övrigt',
  purchase_date date not null default current_date,
  created_at timestamptz not null default now(),
  constraint travel_purchases_amount_check check (amount > 0)
);

create index if not exists travel_budgets_user_start_date_idx
  on public.travel_budgets (user_id, start_date desc);

create index if not exists travel_purchases_budget_date_idx
  on public.travel_purchases (travel_budget_id, purchase_date desc);

alter table if exists public.travel_budgets enable row level security;
alter table if exists public.travel_purchases enable row level security;

drop policy if exists "Users can select their own travel budgets" on public.travel_budgets;
drop policy if exists "Users can insert their own travel budgets" on public.travel_budgets;
drop policy if exists "Users can update their own travel budgets" on public.travel_budgets;
drop policy if exists "Users can delete their own travel budgets" on public.travel_budgets;
create policy "Users can select their own travel budgets" on public.travel_budgets for select using (auth.uid() = user_id);
create policy "Users can insert their own travel budgets" on public.travel_budgets for insert with check (auth.uid() = user_id);
create policy "Users can update their own travel budgets" on public.travel_budgets for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own travel budgets" on public.travel_budgets for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own travel purchases" on public.travel_purchases;
drop policy if exists "Users can insert their own travel purchases" on public.travel_purchases;
drop policy if exists "Users can update their own travel purchases" on public.travel_purchases;
drop policy if exists "Users can delete their own travel purchases" on public.travel_purchases;
create policy "Users can select their own travel purchases" on public.travel_purchases for select using (auth.uid() = user_id);
create policy "Users can insert their own travel purchases" on public.travel_purchases for insert with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.travel_budgets
    where travel_budgets.id = travel_purchases.travel_budget_id
      and travel_budgets.user_id = auth.uid()
  )
);
create policy "Users can update their own travel purchases" on public.travel_purchases for update using (auth.uid() = user_id) with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.travel_budgets
    where travel_budgets.id = travel_purchases.travel_budget_id
      and travel_budgets.user_id = auth.uid()
  )
);
create policy "Users can delete their own travel purchases" on public.travel_purchases for delete using (auth.uid() = user_id);
