create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  title text not null,
  saved numeric not null default 0,
  target numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.savings_accounts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  amount numeric not null default 0,
  created_at timestamptz not null default now()
);
