create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  remaining_amount numeric not null default 0,
  monthly_payment numeric not null default 0,
  interest_rate numeric not null default 0,
  payment_day integer not null default 25,
  created_at timestamptz not null default now(),
  constraint loans_remaining_amount_check check (remaining_amount >= 0),
  constraint loans_monthly_payment_check check (monthly_payment > 0),
  constraint loans_interest_rate_check check (interest_rate >= 0),
  constraint loans_payment_day_check check (payment_day between 1 and 28)
);

create index if not exists loans_user_id_idx
  on public.loans (user_id);

alter table if exists public.loans enable row level security;

drop policy if exists "Users can select their own loans" on public.loans;
drop policy if exists "Users can insert their own loans" on public.loans;
drop policy if exists "Users can update their own loans" on public.loans;
drop policy if exists "Users can delete their own loans" on public.loans;

create policy "Users can select their own loans"
  on public.loans for select
  using (auth.uid() = user_id);

create policy "Users can insert their own loans"
  on public.loans for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own loans"
  on public.loans for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own loans"
  on public.loans for delete
  using (auth.uid() = user_id);
