create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  type text not null default 'bug',
  message text not null,
  page text,
  app_version text,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  constraint feedback_type_check check (type in ('bug', 'idea', 'other')),
  constraint feedback_status_check check (status in ('new', 'reviewed', 'planned', 'done', 'closed'))
);

create index if not exists feedback_user_created_idx
  on public.feedback (user_id, created_at desc);

create index if not exists feedback_status_created_idx
  on public.feedback (status, created_at desc);

alter table if exists public.feedback enable row level security;

drop policy if exists "Users can select their own feedback" on public.feedback;
drop policy if exists "Users can insert their own feedback" on public.feedback;
drop policy if exists "Users can update their own feedback" on public.feedback;
drop policy if exists "Users can delete their own feedback" on public.feedback;

create policy "Users can select their own feedback" on public.feedback for select using (auth.uid() = user_id);
create policy "Users can insert their own feedback" on public.feedback for insert with check (auth.uid() = user_id);
create policy "Users can update their own feedback" on public.feedback for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own feedback" on public.feedback for delete using (auth.uid() = user_id);
