create table if not exists public.investments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  symbol text not null,
  type text not null default 'stock',
  quantity numeric not null,
  average_price numeric not null default 0,
  current_price numeric not null default 0,
  currency text not null default 'SEK',
  price_updated_at timestamptz,
  created_at timestamptz not null default now(),
  constraint investments_type_check check (type in ('stock', 'fund', 'crypto', 'other')),
  constraint investments_quantity_check check (quantity > 0),
  constraint investments_average_price_check check (average_price >= 0),
  constraint investments_current_price_check check (current_price >= 0)
);

create index if not exists investments_user_created_at_idx
  on public.investments (user_id, created_at);

alter table if exists public.investments enable row level security;

drop policy if exists "Users can select their own investments" on public.investments;
drop policy if exists "Users can insert their own investments" on public.investments;
drop policy if exists "Users can update their own investments" on public.investments;
drop policy if exists "Users can delete their own investments" on public.investments;

create policy "Users can select their own investments"
  on public.investments for select
  using (auth.uid() = user_id);

create policy "Users can insert their own investments"
  on public.investments for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own investments"
  on public.investments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own investments"
  on public.investments for delete
  using (auth.uid() = user_id);
