create table if not exists public.profile (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  full_name text,
  monthly_income numeric not null default 0,
  monthly_savings numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table if exists public.profile
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table if exists public.profile
  add column if not exists full_name text;

alter table if exists public.profile
  add column if not exists monthly_income numeric not null default 0;

alter table if exists public.profile
  add column if not exists monthly_savings numeric not null default 0;

alter table if exists public.profile
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists profile_user_id_key
  on public.profile (user_id)
  where user_id is not null;

alter table if exists public.profile enable row level security;

drop policy if exists "Users can select their own profile" on public.profile;
drop policy if exists "Users can insert their own profile" on public.profile;
drop policy if exists "Users can update their own profile" on public.profile;
drop policy if exists "Users can delete their own profile" on public.profile;

create policy "Users can select their own profile"
  on public.profile for select
  using (auth.uid() = user_id);

create policy "Users can insert their own profile"
  on public.profile for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own profile"
  on public.profile for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own profile"
  on public.profile for delete
  using (auth.uid() = user_id);
