create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  weekdays smallint[] not null default array[0,1,2,3,4,5,6]::smallint[],
  created_day date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  constraint habits_name_check check (length(trim(name)) between 1 and 70),
  constraint habits_weekdays_not_empty check (array_length(weekdays, 1) >= 1),
  constraint habits_weekdays_valid check (weekdays <@ array[0,1,2,3,4,5,6]::smallint[])
);

create table if not exists public.habit_pauses (
  id bigint generated by default as identity primary key,
  habit_id bigint not null,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  from_day date not null,
  until_day date,
  created_at timestamptz not null default now(),
  constraint habit_pauses_habit_owner_fkey foreign key (habit_id, user_id)
    references public.habits(id, user_id) on delete cascade,
  constraint habit_pauses_valid_range check (until_day is null or until_day >= from_day)
);

create table if not exists public.habit_checks (
  id bigint generated by default as identity primary key,
  habit_id bigint not null,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  day date not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint habit_checks_habit_owner_fkey foreign key (habit_id, user_id)
    references public.habits(id, user_id) on delete cascade,
  constraint habit_checks_status_check check (status in ('done', 'skipped')),
  unique (user_id, habit_id, day)
);

create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  day date not null,
  text text not null default '',
  mood smallint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint journal_entries_mood_check check (mood between 1 and 5),
  unique (user_id, day)
);

create index if not exists habits_user_created_idx
  on public.habits (user_id, created_at);

create index if not exists habit_pauses_user_habit_idx
  on public.habit_pauses (user_id, habit_id);

create index if not exists habit_checks_user_day_idx
  on public.habit_checks (user_id, day desc);

create index if not exists journal_entries_user_day_idx
  on public.journal_entries (user_id, day desc);

alter table public.habits enable row level security;
alter table public.habit_pauses enable row level security;
alter table public.habit_checks enable row level security;
alter table public.journal_entries enable row level security;

drop policy if exists "Users can select their own habits" on public.habits;
drop policy if exists "Users can insert their own habits" on public.habits;
drop policy if exists "Users can update their own habits" on public.habits;
drop policy if exists "Users can delete their own habits" on public.habits;
create policy "Users can select their own habits" on public.habits for select using (auth.uid() = user_id);
create policy "Users can insert their own habits" on public.habits for insert with check (auth.uid() = user_id);
create policy "Users can update their own habits" on public.habits for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own habits" on public.habits for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own habit pauses" on public.habit_pauses;
drop policy if exists "Users can insert their own habit pauses" on public.habit_pauses;
drop policy if exists "Users can update their own habit pauses" on public.habit_pauses;
drop policy if exists "Users can delete their own habit pauses" on public.habit_pauses;
create policy "Users can select their own habit pauses" on public.habit_pauses for select using (auth.uid() = user_id);
create policy "Users can insert their own habit pauses" on public.habit_pauses for insert with check (auth.uid() = user_id);
create policy "Users can update their own habit pauses" on public.habit_pauses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own habit pauses" on public.habit_pauses for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own habit checks" on public.habit_checks;
drop policy if exists "Users can insert their own habit checks" on public.habit_checks;
drop policy if exists "Users can update their own habit checks" on public.habit_checks;
drop policy if exists "Users can delete their own habit checks" on public.habit_checks;
create policy "Users can select their own habit checks" on public.habit_checks for select using (auth.uid() = user_id);
create policy "Users can insert their own habit checks" on public.habit_checks for insert with check (auth.uid() = user_id);
create policy "Users can update their own habit checks" on public.habit_checks for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own habit checks" on public.habit_checks for delete using (auth.uid() = user_id);

drop policy if exists "Users can select their own journal entries" on public.journal_entries;
drop policy if exists "Users can insert their own journal entries" on public.journal_entries;
drop policy if exists "Users can update their own journal entries" on public.journal_entries;
drop policy if exists "Users can delete their own journal entries" on public.journal_entries;
create policy "Users can select their own journal entries" on public.journal_entries for select using (auth.uid() = user_id);
create policy "Users can insert their own journal entries" on public.journal_entries for insert with check (auth.uid() = user_id);
create policy "Users can update their own journal entries" on public.journal_entries for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own journal entries" on public.journal_entries for delete using (auth.uid() = user_id);
